import { RawAxiosRequestHeaders } from "axios";
import Analytics from "./lib/requests/analytics";
import Automod from "./lib/requests/automod";
import Channel from "./lib/requests/channel";
import Chat from "./lib/requests/chat";
import Clips from "./lib/requests/clips";
import Commercial from "./lib/requests/commercial";
import Events from "./lib/requests/events";
import Games from "./lib/requests/games";
import GuestStar from "./lib/requests/guest_star";
import Markers from "./lib/requests/markers";
import Moderation from "./lib/requests/moderation";
import Polls from "./lib/requests/polls";
import Predictions from "./lib/requests/predictions";
import Rewards from "./lib/requests/rewards";
import Schedule from "./lib/requests/schedule";
import Search from "./lib/requests/search";
import Stream from "./lib/requests/stream";
import Subscriptions from "./lib/requests/subscriptions";
import Teams from "./lib/requests/teams";
import Users from "./lib/requests/users";
import Videos from "./lib/requests/videos";
import EventSub from "./lib/eventsub/websocket";
import TMIClient from "./lib/tmi/websocket";
import Static from "./lib/static";
type HelixInitParams = {
    client_id: string;
    access_token?: string;
    language?: string;
};
declare class Helix extends Static {
    private client_id;
    private language?;
    headers: RawAxiosRequestHeaders;
    analytics: Analytics;
    automod: Automod;
    channel: Channel;
    chat: Chat;
    clips: Clips;
    commercial: Commercial;
    events: Events;
    games: Games;
    guest: GuestStar;
    markers: Markers;
    moderation: Moderation;
    polls: Polls;
    predictions: Predictions;
    rewards: Rewards;
    schedule: Schedule;
    search: Search;
    stream: Stream;
    subscriptions: Subscriptions;
    teams: Teams;
    users: Users;
    videos: Videos;
    EventSub: EventSub;
    tmi: TMIClient;
    constructor(params: HelixInitParams);
    getAuthLink(scopes: string[] | undefined, redirect_uri: string): Promise<string | Error>;
    updateStream(broadcaster_id: string, title: string, game: string): Promise<import("./lib/requests/types/channel").TChannel>;
}
export default Helix;
